[build]
  base = "."
  publish = "dist"
  command = "npm run build:combined"

# Admin dashboard routes (everything under /admin)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Storefront routes (everything else)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://api.tedara.com/backend/public"
